version: '3.7'

services:

  postgres_db:
    image: postgres:latest
    container_name: "postgres_db"
    restart: always
    ports:
      - "54320:5432"
    volumes:
      - ./db_init.sql:/docker-entrypoint-initdb.d/db_init.sql
    environment:
      POSTGRES_PASSWORD: docker
      POSTGRES_DB: mydb
      SCHEMA: public
      ANON: web_anon
      AUTHENTICATOR: authenticator

  quarkus:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.jvm
    depends_on:
      - postgres_db
      - redis
    ports:
      - 8082:8082

  redis:
    image: "redis:alpine"
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    ports:
      - 6379:6379

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080